name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov build
        pip install -e ".[dev]"
    
    - name: Run Ruff linting
      run: |
        ruff check .
    
    - name: Run tests with coverage
      run: |
        pytest --cov=file_encoder --cov-report=xml --cov-report=html --junitxml=pytest-report.xml
    
    - name: Upload coverage XML artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-py${{ matrix.python-version }}
        path: coverage.xml
    
    - name: Upload pytest report artifact
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report-py${{ matrix.python-version }}
        path: pytest-report.xml
    
    - name: Build package
      run: |
        python -m build
    
    - name: Configure AWS credentials
      if: matrix.python-version == '3.13'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Upload to S3
      if: matrix.python-version == '3.13'
      run: |
        aws s3 cp dist/*.whl s3://${{ secrets.S3_BUCKET_NAME }}/
    
    - name: Upload to CodeArtifact
      if: matrix.python-version == '3.13'
      run: |
        aws codeartifact login --tool pip --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --repository ${{ secrets.CODEARTIFACT_REPOSITORY }}
        aws codeartifact login --tool twine --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --repository ${{ secrets.CODEARTIFACT_REPOSITORY }}
        pip install twine
        twine upload --repository codeartifact dist/*.whl
