name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  # Run Python tests and lint on GitHub runner
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
          pip install build ruff pytest pytest-cov

      - name: Lint with ruff
        run: ruff check src/file_encoder

      - name: Test with pytest
        run: |
          export PYTHONPATH=$(pwd)/src
          pytest -v --cov=file_encoder --cov-report=xml:coverage.xml --junitxml=pytest-report.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: matrix.python-version == '3.13'
        with:
          name: test-results
          path: |
            coverage.xml
            pytest-report.xml
          retention-days: 30

  # Trigger CodeBuild for Python 3.13 build, wheel creation, and S3/CodeArtifact upload
  codebuild:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Trigger CodeBuild
        run: |
          echo "Starting CodeBuild project..."
          aws codebuild start-build --project-name github-actions-practice \
            --region ${{ secrets.AWS_DEFAULT_REGION }}
